#!/usr/local/bin/sbcl --script
(defun palindrome-numberp (num)
 (let ((strnum (format nil "~a" num)))
  (equal strnum (reverse strnum))))
(defun product-palindromep (a b)
 (palindrome-numberp (* a b)))
(defun max-product-palindrome (start end)
 (let ((max 0))
  (do ((i start (+ 1 i)))
   ((>= i end) max)
   (do ((j start (+ 1 j)))
    ((>= j end) max)
    (if (and
         (product-palindromep i j)
         (< max (* i j)))
     (setf max (* i j)))))))
(defun euler ()
  (max-product-palindrome 0 1000))
(defun output-to-screen (x)
  (write-line x))
(output-to-screen (format nil "~a" (euler)))
