#!/usr/local/bin/sbcl --script
(defun remainderp (num div)
 (not (zerop (mod num div))))
(defun make-divisor-list (limit)
 (let ((lst nil))
  (do ((i 1 (+ 1 i)))
   ((> i limit) lst)
   (push i lst))))
(defun div-over-list (num lst)
    (dolist (div lst t)
      (if (remainderp num div)
        (return nil))))
(defun euler ()
 (let ((lst (make-divisor-list 20)))
  (do ((i 1 (+ 1 i)))
   (nil)
   (if (div-over-list i lst)
    (return i)))))
(defun output-to-screen (x)
  (write-line x))
(output-to-screen (format nil "~a" (euler)))
