#!/usr/local/bin/sbcl --script
(defun pythagoreanp (a b c)
 (eql (+ (* a a) (* b b)) (* c c)))
(defun add-to-limit (a b c limit)
 (eql (+ a b c) limit))
(defun euler ()
 (let ((prod 0))
  (do ((a 1 (+ 1 a)))
   ((> a 997) prod)
  (do ((b 1 (+ 1 b)))
   ((> b 997) prod)
  (do ((c 1 (+ 1 c)))
   ((> c 997) prod)
   (if (and
        (add-to-limit a b c 1000)
        (pythagoreanp a b c))
    (setf prod (* a b c))))))))
(defun output-to-screen (x)
  (write-line x))
(output-to-screen (format nil "~a" (euler)))
