#!/usr/local/bin/sbcl --script
(defun make-number-list (limit)
 (let ((lst nil))
  (do ((i 1 (+ 1 i)))
   ((> i limit) lst)
   (push i lst))))
(defun factorial (num)
 (apply #'* (make-number-list num)))
(defun string-to-number-list (str)
 (let ((lst nil))
  (do ((i 0 (+ 1 i)))
   ((>= i (length str)) lst)
    (push (parse-integer str :start i :end (+ 1 i)) lst))))
(defun euler ()
 (apply #'+ (string-to-number-list (format nil "~A" (factorial 100)))))
(defun output-to-screen (x)
  (write-line x))
(output-to-screen (format nil "~A" (euler)))
