#!/usr/local/bin/sbcl --script
(let ((fiblist (list 1 1)))
 (defun next-fib()
   (+ (first fiblist) (second fiblist)))
  (defun push-next-fib ()
    (push (next-fib) fiblist))
  (defun current-fib()
    (first fiblist))
  (defun current-fib-term-index()
   (length fiblist))
  (defun current-fib-length()
   (length (format nil "~A" (current-fib)))))
(defun euler ()
 (progn
  (loop until (>= (current-fib-length) 1000)
  do (push-next-fib))
  (current-fib-term-index)))
(defun output-to-screen (x)
  (write-line x))
(output-to-screen (format nil "~a" (euler)))
