#!/usr/local/bin/sbcl --script
(defun palindrome-base10 (num)
 (let ((strnum (format nil "~A" num)))
  (equal strnum (reverse strnum))))
(defun palindrome-base2 (num)
 (let ((strnum (format nil "~B" num)))
  (equal strnum (reverse strnum))))
(defun list-palindromes (limit)
 (let ((result nil))
  (do ((i 0 (+ 1 i)))
   ((>= i limit) result)
   (if (and
        (palindrome-base10 i)
        (palindrome-base2 i))
    (push i result)))))
(defun euler ()
 (apply #'+ (list-palindromes 1000000)))
(defun output-to-screen (x)
  (write-line x))
(output-to-screen (format nil "~a" (euler)))
